name: Check New Tags, Sync with Upstream, Build and Push Multi-Architecture Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование основного репозитория
      - name: Clone main repository
        run: git clone https://github.com/allure-framework/allurectl.git ./allurectl_repo

      # Шаг 2: Получение тегов из основного репозитория
      - name: Fetch tags from main repository
        run: |
          cd ./allurectl_repo
          LATEST_GITHUB_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          echo "LATEST_GITHUB_TAG=$LATEST_GITHUB_TAG" >> $GITHUB_ENV
          cd ..
      # Шаг 3: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Шаг 4: Сравнение тегов и сборка, если есть новый
      - name: Compare tags and build if new
        if: ${{ env.LATEST_GITHUB_TAG != env.DOCKERHUB_LATEST_TAG }}
        run: |
          echo 'FROM docker:23' > Dockerfile
          echo 'RUN apk add bash git gettext curl' >> Dockerfile
          echo 'ARG ARCH' >> Dockerfile
          echo 'ARG LATEST_GITHUB_TAG' >> Dockerfile
          echo 'ADD https://github.com/allure-framework/allurectl/releases/download/${LATEST_GITHUB_TAG}/allurectl_linux_${TARGETARCH} /bin/allurectl' >> Dockerfile
          echo 'RUN chmod +x /bin/allurectl' >> Dockerfile
          # Настройка Docker Buildx
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64/v8 --tag erolatex/allurectl:${LATEST_GITHUB_TAG} --tag erolatex/allurectl:latest --push --build-arg LATEST_GITHUB_TAG=${LATEST_GITHUB_TAG} .
