
name: Check New Tags, Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаги 1 и 2: Клонирование репозитория и получение тегов...
      - name: Clone main repository
        run: git clone https://github.com/allure-framework/allurectl.git ./allurectl_repo

      - name: Fetch tags from main repository
        run: |
          cd ./allurectl_repo
          LATEST_GITHUB_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          echo "LATEST_GITHUB_TAG=$LATEST_GITHUB_TAG" >> $GITHUB_ENV
          cd ..

      - name: Check out the repo
        uses: actions/checkout@v2

      # Шаг: Проверка наличия тега на Docker Hub
      - name: Check if Docker image tag exists
        id: docker-hub-tag-exists
        uses: satak/get-docker-hub-tag@v1
        with:
          repository: erolatex/allurectl
          tag: ${{ env.LATEST_GITHUB_TAG }}

      # Шаг 2: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Шаг 3: Сборка и публикация Docker образа (пропуск, если тег уже существует)
      - name: Build and push Docker images
        if: steps.docker-hub-tag-exists.outputs.exists != 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            erolatex/allurectl:latest
            erolatex/allurectl:${{ env.LATEST_GITHUB_TAG }}
          platforms: linux/amd64,linux/arm64
