
name: Check New Tags, Build and Push Multi-Architecture Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование основного репозитория
      - name: Clone main repository
        run: git clone https://github.com/allure-framework/allurectl.git ./allurectl_repo

      # Шаг 2: Получение тегов из основного репозитория
      - name: Fetch tags from main repository
        run: |
          cd ./allurectl_repo
          LATEST_GITHUB_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          echo "LATEST_GITHUB_TAG=$LATEST_GITHUB_TAG" >> $GITHUB_ENV
          cd ..

      # Шаг 3: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Шаг 4: Сборка и публикация Docker образа
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --platform linux/amd64,linux/arm64/v8 --tag erolatex/allurectl:${LATEST_GITHUB_TAG} --tag erolatex/allurectl:latest --push .
