
name: Check New Tags, Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Запуск каждый день в полночь

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаги 1 и 2: Клонирование репозитория и получение тегов...
      - name: Clone main repository
        run: git clone https://github.com/allure-framework/allurectl.git ./allurectl_repo

      - name: Fetch tags from main repository
        run: |
          cd ./allurectl_repo
          LATEST_GITHUB_TAG=$(git tag -l --sort=-v:refname | head -n 1)
          echo "LATEST_GITHUB_TAG=$LATEST_GITHUB_TAG" >> $GITHUB_ENV
          cd ..

      # Шаг: Проверка наличия тега на Docker Hub
      - name: Check if tag exists on Docker Hub
        run: |
          TAG_EXISTS=$(curl -s -o /dev/null -w '%{http_code}' https://hub.docker.com/v2/repositories/erolatex/allurectl/tags/${{ env.LATEST_GITHUB_TAG }}/)
          if [ "$TAG_EXISTS" = "200" ]; then
            echo "Tag ${LATEST_GITHUB_TAG} already exists on Docker Hub."
            echo "SKIP_PUSH=true" >> $GITHUB_ENV
          else
            echo "Tag ${LATEST_GITHUB_TAG} does not exist. Proceeding to push."
            echo "SKIP_PUSH=false" >> $GITHUB_ENV
          fi

       # Шаг: Установка и настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    

      # Шаг 3: Сборка и публикация Docker образа (пропуск, если тег уже существует)
      - name: Build and push Docker images
        if: env.SKIP_PUSH == 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            erolatex/allurectl:latest
            erolatex/allurectl:${{ env.LATEST_GITHUB_TAG }}
          platforms: linux/amd64,linux/arm64
